apiVersion: v2
name: webtop-data-science
description: Webtop VNC for data science
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webtop-logo.png
keywords:
  - Webtop
  - Python
  - Java
  - VNC
home: https://docs.linuxserver.io/images/docker-webtop/
sources:
  - https://github.com/InseeFrLab/images-datascience
  - https://github.com/Tetras-Libre/helm-charts-interactive-services
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.25
dependencies:
  - name: library-chart
    version: 1.7.13
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
